# Workflow name
name: "Chromatic Publish"

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

# List of jobs
jobs:
    publish:
        # Operating System
        runs-on: ubuntu-latest
        # Job steps
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # 👈 Required to retrieve git history

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
              run: yarn

            - name: Build Storybook
              run: yarn build-storybook   

              # 👇 Adds Chromatic as a step in the workflow
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              # Chromatic GitHub Action options
              with:
                  # 👇 Chromatic projectToken, refer to the manage page to obtain it.
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
